apiVersion: apps/v1
kind: Deployment
metadata:
  name: fra-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fra-backend
  template:
    metadata:
      labels:
        app: fra-backend
    spec:
      containers:
        - name: backend
          image: fra-backend:latest
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: fra-env
---
apiVersion: v1
kind: Service
metadata:
  name: fra-backend
spec:
  selector:
    app: fra-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
